name: Pylint

on: [push]

jobs:
  pylint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Python lint
        uses: ricardochaves/python-lint@v1.4.0
        with:
          python-root-list: "."
          use-pylint: true
          use-pycodestyle: false
          use-flake8: true
          use-black: false
          use-mypy: false
          use-isort: false
          extra-pylint-options: "--max-line-length=120 --disable=C0301 --disable=C0116 --exclude=__init__.py,__pycache__,.git"
          extra-pycodestyle-options: ""
          extra-flake8-options: "--max-line-length=120 --ignore=E501 --exclude=gcp,colab"
          extra-black-options: ""
          extra-mypy-options: ""
          extra-isort-options: ""
